# Name of the workflow
name: Build CPython WASM and Upload

# Define when the workflow will run
on:
  # Trigger the workflow on push events to the 'main' branch
  push:
    branches:
      - main
  # Allow manual triggering of the workflow from the GitHub Actions UI
  workflow_dispatch:

# Grant necessary permissions to the GITHUB_TOKEN for pushing files
permissions:
  contents: write # Required for committing and pushing files to the repository

# Define the jobs to be executed in this workflow
jobs:
  build_wasm:
    # Specify the runner environment for this job
    # Ubuntu is typically used for Emscripten builds
    runs-on: ubuntu-latest

    # Define the steps to be executed in this job
    steps:
      # Step 1: Checkout the current repository
      # This action checks out your repository under $GITHUB_WORKSPACE,
      # which is necessary for committing the compiled files later.
      - name: Checkout current repository
        uses: actions/checkout@v4

      # Step 2: Get the short commit hash of the current HEAD
      # This step gets the first 7 characters of the commit hash,
      # which is commonly used as a short, unique identifier.
      - name: Get short commit hash
        id: get_commit_hash # Assign an ID to this step to reference its outputs
        run: |
          # Get the short commit hash (e.g., 'abcdef1')
          COMMIT_HASH=$(git rev-parse --short HEAD)
          # Output the commit hash, making it available to subsequent steps
          echo "commit_hash=$COMMIT_HASH" >> "$GITHUB_OUTPUT"
          echo "Discovered short commit hash: $COMMIT_HASH"

      # Step 3: Set up Python environment
      # CPython's build process and Emscripten's requirements often depend on Python.
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use a recent stable Python 3 version

      # Step 4: Set up Emscripten SDK
      # This step clones the Emscripten SDK, installs the latest version,
      # activates it, and adds its binary directory to the PATH for subsequent steps.
      - name: Set up Emscripten SDK
        run: |
          echo "Setting up Emscripten SDK..."
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest # Install the latest Emscripten SDK
          ./emsdk activate latest --permanent # Activate it and configure environment variables
          # Find the directory containing 'emcc' after activation
          EMSDK_DIR=$(pwd)
          EMCC_PATH=$(find "$EMSDK_DIR" -name "emcc" -print -quit)
          EMCC_BIN_DIR=$(dirname "$EMCC_PATH")
          # Add the Emscripten binary directory to the PATH for all subsequent steps
          echo "$EMCC_BIN_DIR" >> "$GITHUB_PATH"
          # Store the EMSDK root directory as an environment variable for later reference
          echo "EMSDK_ROOT=$EMSDK_DIR" >> "$GITHUB_ENV"
          echo "Emscripten SDK setup complete. emcc is now in PATH."

      # Step 5: Clone the CPython repository
      # This gets the source code for CPython.
      - name: Clone CPython repository
        run: |
          echo "Cloning CPython repository..."
          git clone https://github.com/python/cpython.git
          echo "CPython repository cloned."

      # Step 6: Build CPython for WebAssembly using Emscripten
      # This step navigates into the CPython directory and runs the Emscripten build process.
      # It assumes the standard CPython WASM build process found in `Tools/wasm`.
      - name: Build CPython for WebAssembly
        working-directory: ./cpython # Execute commands from the cpython directory
        run: |
          echo "Building CPython for WebAssembly..."
          # Source the emsdk environment script again to ensure all tools are available
          # This is crucial because each 'run' step starts a new shell.
          source "${{ env.EMSDK_ROOT }}/emsdk_env.sh"
          # Create and activate a Python virtual environment for build dependencies
          python3 -m venv .venv
          source .venv/bin/activate
          # Run the Emscripten build command for CPython using the recommended script
          # This command typically compiles CPython into python.js and python.wasm
          python Tools/wasm/emscripten build
          echo "CPython WASM build complete."

      # Step 7: Prepare and rename compiled files for upload
      # This step creates the target directory named after the commit hash
      # and copies the entire contents of the build directory into it.
      - name: Prepare compiled files for upload
        run: |
          COMMIT_HASH="${{ steps.get_commit_hash.outputs.commit_hash }}"
          echo "Preparing build directory for commit hash: $COMMIT_HASH"
          # Define the source directory where Emscripten build outputs are expected
          CPYTHON_BUILD_DIR="cpython/cross-build/wasm32-emscripten/build"
          # Define the target directory in your repo where the build will be copied
          TARGET_UPLOAD_DIR="compiled/$COMMIT_HASH"

          # --- DEBUGGING STEP: List contents of the expected build directory ---
          echo "Listing contents of CPython build directory: $CPYTHON_BUILD_DIR"
          ls -l "$CPYTHON_BUILD_DIR"
          # --- END DEBUGGING STEP ---

          # Create the target directory named after the commit hash
          mkdir -p "$TARGET_UPLOAD_DIR"
          # Copy the entire contents of the CPython build directory to the target upload directory
          # The 'cp -r' command recursively copies the directory contents.
          cp -r "$CPYTHON_BUILD_DIR"/* "$TARGET_UPLOAD_DIR"/
          echo "Contents of CPython build directory copied to: $TARGET_UPLOAD_DIR"
          ls -l "$TARGET_UPLOAD_DIR"

      # Step 8: Commit and push the compiled files to the repository
      # This step configures Git, adds the new/updated files, commits them, and pushes to the repo.
      - name: Commit and push compiled files
        run: |
          COMMIT_HASH="${{ steps.get_commit_hash.outputs.commit_hash }}"
          echo "Committing and pushing compiled build folder..."
          # Configure Git user for the commit
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # Add the entire compiled folder to the Git staging area
          git add compiled/"$COMMIT_HASH"
          # Commit the changes. The '|| echo "No changes to commit"' prevents the workflow
          # from failing if the files haven't actually changed since the last commit.
          git commit -m "feat: Upload CPython WASM build folder for commit $COMMIT_HASH" || echo "No changes to commit"
          # Push the changes to the remote repository
          git push
          echo "Compiled build folder pushed to repository."
